---
title: "Analise da atividade dos parlamentares no Twitter no ano de 2019"
author: "Alice Fernandes Silva, Elton Dantas de Oliveira Mesquita, Igor Matheus Castor Diniz Pinheiro"
theme: sandstone
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
  html_notebook:
    toc: yes
    toc_float: yes
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(gridExtra)
source(here::here("code/lib.R"))
theme_set(theme_bw())
options(scipen = 999)
```

```{r read}
atividade = read_projectdata()
glimpse(atividade)
```

##Levando em consideração os parlamentares e seus respectivos alcances em redes sociais, Quais são os partidos que possuem o maior poder de influência no twitter?

```{r}
engaj_mediano_partido = 
  atividade %>%
  na.omit(engaj_mediano) %>%
  group_by(partido) %>%
  filter(partido != 'S/Partido') %>%
  summarise(engaj_med_part = median(engaj_mediano))

engaj_mediano_partido %>%
  group_by(partido)%>%
  ggplot(aes(x= reorder(partido, engaj_med_part), y= engaj_med_part,fill = partido) ) +
  geom_col(show.legend = FALSE)+
  labs(y='engajamento_mediano_do_partido', x= 'partidos')+
  coord_flip()

```

##Os deputados que são filiados ao PSL e PSOL são ativos no twitter assim como o atual presidente da república?


```{r}
camara_psl_psol = atividade %>%
    filter(casa == "câmara") %>%
  filter(partido == "PSL" | partido == "PSOL") %>%
  filter(twitter != "NA")
glimpse(camara_psl_psol)
```
```{r}
grafico1 = camara_psl_psol %>%
  filter(partido=="PSL") %>% 
  ggplot(mapping = aes(x = engaj_total, y = nome_eleitoral)) +
  geom_jitter()

grafico2 = camara_psl_psol %>%
  filter(partido=="PSOL") %>% 
  ggplot(mapping = aes(x = engaj_total, y = nome_eleitoral)) +
  geom_jitter()
  
grid.arrange(grafico1, grafico2, ncol=2)
```






